# Generated by Django 6.0.7 on 2026-08-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Story",
        ),
    ]
